### PR TITLE
Java 11 changes

### PR DESCRIPTION
**Pull request by jberkel**
Needs merging of osr-common changes first (https://github.com/sweble/osr-common/pull/9)

### CODE REVIEW

**Comment by wetneb** [comment]
I just re-run the CI here, after merging your changes to `osr-common`, but it looks like we still have a failing test.

**Comment by wetneb** [comment]
(Or perhaps there is some caching somewhere and you actually need to push a new commit here? Not sure)

**Comment by jberkel** [comment]
It looks like a problem with Java 8, I'll have a look. Is it possible to set up the CI so that the Java 11 build always  finishes, even if Java 8 fails? Right now, it looks like it gets cancelled as soon as the other build fails.

**Review by wetneb — APPROVED** [review]

**Comment by wetneb** [comment]
Thank you so much!

**Pull request merged**
